version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: local-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pat
      MONGO_INITDB_ROOT_PASSWORD: password123

volumes:
  mongodb_data:
    driver: local
